# Project configuration
general:
  projectName: 'RiskManagement'
  productiveBranch: 'main'

# Stage configuration
stages:
  productionDeployment:
    cfTargets:
    - org: 'a064614atrial'
      space: 'dev'
      appName: 'RiskManagement'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      credentialsId: 'cfdeploy'